version: "2"

services:

  db:
    image: postgres:9.5
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:

  app:
    env_file: .env
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3002:3001"
    depends_on:
      - db